baseURL = "/"         
languageCode = 'ru-ru'
title = 'Проект по социально-экономическим показателям стран'
theme = 'ananke'
publishDir = "../site"  # Генерировать сайт в соседнюю папку

[permalinks]
    pages = "/:slug/"       
    journal = "/journal/:filename/"  

[[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "О проекте"
    url = "/о-проекте/"
    weight = 2

[[menu.main]]
    identifier = "team"
    name = "Участники"
    url = "/участники/"
    weight = 3

[[menu.main]]
    identifier = "resources"
    name = "Ресурсы"
    url = "/ресурсы/"
    weight = 4


[[menu.main]]
    identifier = "journal"
    name = "Журнал"
    url = "/journal/"
    weight = 10