baseURL = "/"         
languageCode = 'ru-ru'
title = 'Проект по социально-экономическим показателям стран'
theme = 'ananke'
publishDir = "../site"  # Генерировать сайт в соседнюю папку

[permalinks]
    pages = "/:slug/" 